import type { Metadata } from "next";
import "./globals.scss";
import {bodyFont} from "@/app/ui/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bodyFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
